from __future__ import annotations

import base64
import binascii
from datetime import date, datetime, timedelta
from typing import Any, Literal

from pydantic import AnyHttpUrl, BaseModel, EmailStr, Field, TypeAdapter, field_validator, model_validator

ExportFormat = Literal["csv", "zip"]
_EMAIL_VALIDATOR = TypeAdapter(EmailStr)
_URL_VALIDATOR = TypeAdapter(AnyHttpUrl)
SUPPORT_ATTACHMENT_MAX_BYTES = 5 * 1024 * 1024
SUPPORT_ATTACHMENT_MAX_COUNT = 3
EARLIEST_DATA_DATE = date(2015, 1, 1)
RUN_START_DATE_MIN = date(2021, 1, 1)
RUN_START_DATE_MAX_LOOKBACK_DAYS = 120
RUN_N_TOP_COINS_MIN = 30
RUN_N_TOP_COINS_MAX = 300
RUN_LOOKBACK_DAYS_MIN = 90
RUN_LOOKBACK_DAYS_MAX = 720
RUN_WINDOW_SIZE_MIN = 14
RUN_WINDOW_SIZE_MAX = 120
RUN_FORECAST_HORIZON_MIN = 7
RUN_FORECAST_HORIZON_MAX = 60
RUN_TOTAL_ASSETS_MIN = 5
RUN_TOTAL_ASSETS_MAX = 30
RUN_RISK_MIN_WEIGHT_MIN = 0.005
RUN_RISK_MIN_WEIGHT_MAX = 0.08
RUN_RISK_MAX_WEIGHT_MIN = 0.12
RUN_RISK_MAX_WEIGHT_MAX = 0.45
RUN_WEIGHT_CAP_MIN = 0.08
RUN_WEIGHT_CAP_MAX = 0.30
RUN_VOL_FLOOR_RATIO_MIN = 0.25
RUN_VOL_FLOOR_RATIO_MAX = 0.70
RUN_GATING_TOLERANCE_MAX = 0.10
_BOOLEAN_TRUTHY = {"true", "1", "yes", "y", "on"}
_BOOLEAN_FALSY = {"false", "0", "no", "n", "off"}
_CTA_EVENT_TYPES = {"cta_click", "signup_started", "email_confirmed", "paid"}


class RunRequest(BaseModel):
    n_top_coins: int = Field(100, ge=RUN_N_TOP_COINS_MIN, le=RUN_N_TOP_COINS_MAX)
    start_date: str | None = Field(
        default=None,
        description="Optional start date in YYYY-MM-DD format.",
        examples=["2023-01-01"],
    )
    lookback_days: int = Field(180, ge=RUN_LOOKBACK_DAYS_MIN, le=RUN_LOOKBACK_DAYS_MAX)
    window_size: int = Field(30, ge=RUN_WINDOW_SIZE_MIN, le=RUN_WINDOW_SIZE_MAX)
    forecast_horizon: int = Field(30, ge=RUN_FORECAST_HORIZON_MIN, le=RUN_FORECAST_HORIZON_MAX)
    advanced_forecast: bool = True
    fresh_data: bool = False
    info_messages: bool = False
    visualization: bool = False
    total_assets: int = Field(10, ge=RUN_TOTAL_ASSETS_MIN, le=RUN_TOTAL_ASSETS_MAX)
    clustering_metric: str = Field(
        "sharpe",
        min_length=1,
        max_length=64,
        description="Metric used inside select_assets_balanced (e.g., 'sharpe').",
    )
    risk_min_weight: float = Field(0.03, ge=RUN_RISK_MIN_WEIGHT_MIN, le=RUN_RISK_MIN_WEIGHT_MAX)
    risk_max_weight: float = Field(0.25, ge=RUN_RISK_MAX_WEIGHT_MIN, le=RUN_RISK_MAX_WEIGHT_MAX)
    weight_cap: float = Field(0.15, ge=RUN_WEIGHT_CAP_MIN, le=RUN_WEIGHT_CAP_MAX)
    vol_floor_ratio: float = Field(0.4, ge=RUN_VOL_FLOOR_RATIO_MIN, le=RUN_VOL_FLOOR_RATIO_MAX)
    gating_tolerance: float = Field(0.02, ge=0.0, le=RUN_GATING_TOLERANCE_MAX)
    run_id: str | None = Field(
        default=None,
        min_length=3,
        max_length=64,
        pattern=r"^[A-Za-z0-9_.\-]+$",
        description="Optional identifier for the run; autogenerated when omitted.",
    )

    @field_validator("start_date", mode="before")
    @classmethod
    def _ensure_valid_start_date(cls, value: object | None) -> str | None:
        if value is None:
            return None
        if isinstance(value, date):
            return value.strftime("%Y-%m-%d")
        if isinstance(value, datetime):
            return value.date().strftime("%Y-%m-%d")
        if isinstance(value, str):
            stripped = value.strip()
            if not stripped or stripped.lower() == "string":
                return None
            try:
                datetime.strptime(stripped, "%Y-%m-%d")
            except ValueError as exc:
                raise ValueError("start_date must match YYYY-MM-DD") from exc
            return stripped
        raise TypeError("start_date must be a date or ISO string")

    @field_validator("advanced_forecast", "fresh_data", "info_messages", "visualization", mode="before")
    @classmethod
    def _normalize_boolean(cls, value: object) -> bool:
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().lower()
            if lowered in _BOOLEAN_TRUTHY:
                return True
            if lowered in _BOOLEAN_FALSY:
                return False
        raise ValueError("Boolean field must be true/false.")

    @field_validator("run_id", mode="before")
    @classmethod
    def _trim_run_id(cls, value: object | None) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            stripped = value.strip()
            return stripped or None
        raise TypeError("run_id must be a string.")

    @model_validator(mode="after")
    def _validate_constraints(self) -> RunRequest:
        if self.risk_max_weight < self.risk_min_weight:
            raise ValueError("risk_max_weight must be greater or equal to risk_min_weight.")
        if self.total_assets > self.n_top_coins:
            raise ValueError("total_assets must be less or equal to n_top_coins.")
        if self.risk_min_weight * self.total_assets > 1.0 + 1e-9:
            raise ValueError("risk_min_weight too high for the requested asset count (sum would exceed 1).")
        risk_min_weight_max = min(RUN_RISK_MIN_WEIGHT_MAX, 1.0 / self.total_assets)
        if self.risk_min_weight > risk_min_weight_max + 1e-9:
            raise ValueError(
                "risk_min_weight exceeds the allowed maximum for the requested asset count."
            )
        weight_cap_min = max(RUN_WEIGHT_CAP_MIN, 1.0 / self.total_assets)
        if self.weight_cap < weight_cap_min - 1e-9:
            raise ValueError("weight_cap must be at least max(0.08, 1 / total_assets).")
        if self.lookback_days < self.window_size:
            raise ValueError("lookback_days must be greater or equal to window_size.")
        if self.forecast_horizon > self.window_size:
            raise ValueError("forecast_horizon must be less or equal to window_size.")
        if self.forecast_horizon > self.lookback_days:
            raise ValueError("forecast_horizon must be less or equal to lookback_days.")
        if self.gating_tolerance > RUN_GATING_TOLERANCE_MAX:
            raise ValueError("gating_tolerance must be 0.10 or less.")
        if self.run_id:
            if self.run_id[0] in {".", "-", "_"}:
                raise ValueError("run_id cannot start with '.', '-', or '_'.")

        if self.start_date:
            parsed = datetime.strptime(self.start_date, "%Y-%m-%d").date()
            if parsed > date.today():
                raise ValueError("start_date cannot be in the future.")
            if parsed < RUN_START_DATE_MIN:
                raise ValueError(f"start_date cannot be earlier than {RUN_START_DATE_MIN.isoformat()}")
            latest_allowed = date.today() - timedelta(days=max(self.lookback_days, RUN_START_DATE_MAX_LOOKBACK_DAYS))
            if parsed > latest_allowed:
                raise ValueError("start_date is too recent for the requested history window.")
            window_start = parsed - timedelta(days=self.lookback_days)
            if window_start < EARLIEST_DATA_DATE:
                raise ValueError(
                    f"lookback_days window exceeds available history from {EARLIEST_DATA_DATE.isoformat()}."
                )
        return self


class RunResponse(BaseModel):
    run_id: str
    weights: dict[str, float]
    perf: dict[str, float]


class RunAcceptedResponse(BaseModel):
    run_id: str
    state: Literal["running", "pending"] = "running"


class RunProgressStage(BaseModel):
    key: str
    label: str
    status: Literal["pending", "running", "done", "error", "cancelled"]
    message: str | None = None
    updated_at: datetime | None = None


class RunProgressLog(BaseModel):
    ts: datetime
    stage: str | None = None
    message: str


class RunProgressResponse(BaseModel):
    run_id: str
    state: Literal["pending", "running", "done", "error", "cancelled"]
    started_at: datetime
    updated_at: datetime
    active_stage_label: str | None = None
    active_stage_status: Literal["pending", "running", "done", "error", "cancelled"] | None = None
    last_message: str | None = None
    status_line: str | None = None
    stages: list[RunProgressStage]
    logs: list[RunProgressLog]


class RunResultCachedResponse(BaseModel):
    run_id: str
    state: Literal["pending", "running", "done", "error", "cancelled"]
    weights: dict[str, float] | None = None
    perf: dict[str, float] | None = None
    cached_at: datetime | None = None


class WeightEntry(BaseModel):
    asset: str
    weight: float


class WeightsResponse(BaseModel):
    run_id: str
    items: list[WeightEntry]


class PerfResponse(BaseModel):
    run_id: str
    metrics: dict[str, float]


class HealthResponse(BaseModel):
    status: Literal["ok"]
    version: str
    timestamp: datetime
    uptime_seconds: float = Field(..., ge=0.0)
    rate_limit: dict[str, int]
    data_paths: dict[str, str]


class PerformanceSeriesPoint(BaseModel):
    x: float
    y: float
    value: float
    value_text: str
    date: str
    date_label: str


class PerformanceSeriesPaths(BaseModel):
    line_path: str
    fill_path: str | None = None
    marker_x: float
    marker_y: float
    points: list[PerformanceSeriesPoint]


class PerformanceAxisTick(BaseModel):
    coordinate: float
    label: str
    value: float | str


class PerformanceChartAxes(BaseModel):
    x_ticks: list[PerformanceAxisTick]
    y_ticks: list[PerformanceAxisTick]


class PerformanceLegendItem(BaseModel):
    css_modifier: str
    label: str
    delta_text: str


class PerformanceMetricCard(BaseModel):
    label: str
    badge_text: str
    badge_modifier: str
    value_text: str
    delta_text: str
    delta_modifier: str
    note: str


class PerformanceSnapshotModel(BaseModel):
    strategy_key: str
    strategy_label: str
    strategy_description: str
    chart_period_label: str
    chart_caption: str
    chart_paths: dict[str, PerformanceSeriesPaths]
    chart_axes: PerformanceChartAxes
    legend: list[PerformanceLegendItem]
    metric_cards: list[PerformanceMetricCard]


class LiveBacktestSeriesPoint(BaseModel):
    date: str
    value: float


class LiveBacktestCalculationBasis(BaseModel):
    frequency: str
    currency: str
    timestamp_policy: str


class LiveBacktestPayloadModel(BaseModel):
    live_start_date: str | None = None
    backtest_window_start: str
    backtest_window_end: str
    fees_included: bool
    slippage_included: bool
    has_live_history: bool
    is_live_series_short: bool
    live_series: list[LiveBacktestSeriesPoint]
    backtest_series: list[LiveBacktestSeriesPoint]
    benchmark_series: list[LiveBacktestSeriesPoint] = Field(default_factory=list)
    live_source: str | None = None
    backtest_source: str
    calculation_basis: LiveBacktestCalculationBasis


class PerformanceResponse(BaseModel):
    default_key: str
    snapshots: dict[str, PerformanceSnapshotModel]
    live_backtest: LiveBacktestPayloadModel | None = None
    live_backtest_by_strategy: dict[str, LiveBacktestPayloadModel | None] = Field(default_factory=dict)


class IndexCompositionAsset(BaseModel):
    rank: int
    asset: str
    weight_pct: float
    weight: float
    cumulative_pct: float
    relative_to_mean: float


class IndexCompositionSummary(BaseModel):
    count: int
    top3_pct: float
    herfindahl: float
    effective_assets: float | None = None
    max_weight_pct: float
    min_weight_pct: float
    mean_weight_pct: float
    total_weight_pct: float


class IndexCompositionDownloads(BaseModel):
    csv: str
    zip: str


class MonthlyCompositionSnapshotModel(BaseModel):
    month: str
    asset: str
    weight: float
    source: str
    run_id: str


class IndexCompositionResponse(BaseModel):
    run_id: str
    updated_display: str
    updated_iso: str
    assets: list[IndexCompositionAsset]
    summary: IndexCompositionSummary
    downloads: IndexCompositionDownloads
    live_backtest: LiveBacktestPayloadModel | None = None
    live_backtest_by_strategy: dict[str, LiveBacktestPayloadModel | None] = Field(default_factory=dict)
    monthly_snapshots: list[MonthlyCompositionSnapshotModel] = Field(default_factory=list)
    monthly_live_snapshots: list[MonthlyCompositionSnapshotModel] = Field(default_factory=list)
    monthly_backtest_snapshots: list[MonthlyCompositionSnapshotModel] = Field(default_factory=list)
    monthly_snapshots_updated_at: str | None = None
    monthly_snapshots_current_month: str | None = None
    monthly_snapshots_default_strategy: str | None = None
    monthly_snapshots_by_strategy: dict[str, list[MonthlyCompositionSnapshotModel]] = Field(default_factory=dict)
    monthly_live_snapshots_by_strategy: dict[str, list[MonthlyCompositionSnapshotModel]] = Field(default_factory=dict)
    monthly_backtest_snapshots_by_strategy: dict[str, list[MonthlyCompositionSnapshotModel]] = Field(default_factory=dict)
    monthly_snapshots_updated_at_by_strategy: dict[str, str | None] = Field(default_factory=dict)
    monthly_snapshots_current_month_by_strategy: dict[str, str | None] = Field(default_factory=dict)


class DemoRequest(BaseModel):
    name: str = Field(..., min_length=2, max_length=120)
    email: EmailStr
    company: str | None = Field(default=None, max_length=120)
    role: str | None = Field(default=None, max_length=80)
    team_size: str | None = Field(default=None, max_length=60)
    use_case: str = Field(..., min_length=10, max_length=600)
    run_id: str | None = Field(
        default=None,
        min_length=3,
        max_length=64,
        pattern=r"^[A-Za-z0-9_.\-]+$",
        description="Optional run identifier to link context for the request.",
    )
    notes: str | None = Field(default=None, max_length=800)
    newsletter_opt_in: bool = False
    terms_accepted: bool = Field(
        ...,
        description="Explicit confirmation that the user agrees with the terms.",
    )

    @field_validator("company", "role", "team_size", mode="before")
    @classmethod
    def _normalize_optional_text(cls, value: object | None) -> str | None:
        return _strip_or_none(value)

    @field_validator("terms_accepted")
    @classmethod
    def _ensure_terms_accepted(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("terms_accepted must be true.")
        return value


class DemoRequestResponse(BaseModel):
    request_id: str
    received_at: datetime


def _strip_or_none(value: object | None) -> str | None:
    if value is None:
        return None
    if isinstance(value, str):
        stripped = value.strip()
        return stripped or None
    return str(value)


class RegistrationRequest(BaseModel):
    full_name: str = Field(..., min_length=2, max_length=120)
    email: EmailStr
    company: str | None = Field(default=None, max_length=160)
    role: str | None = Field(default=None, max_length=80)
    team_size: str | None = Field(default=None, max_length=60)
    objectives: str = Field(..., min_length=10, max_length=600)
    newsletter_opt_in: bool = False
    terms_accepted: bool = Field(
        ...,
        description="Explicit confirmation that the user agrees with the terms.",
    )

    @field_validator("company", "role", "team_size", mode="before")
    @classmethod
    def _normalize_optional_text(cls, value: object | None) -> str | None:
        return _strip_or_none(value)

    @field_validator("objectives", mode="before")
    @classmethod
    def _normalize_objectives(cls, value: object | None) -> str:
        if value is None:
            raise ValueError("objectives is required.")
        if isinstance(value, str):
            stripped = value.strip()
            if not stripped:
                raise ValueError("objectives must not be blank.")
            return stripped
        return str(value)

    @field_validator("terms_accepted")
    @classmethod
    def _ensure_terms_accepted(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("terms_accepted must be true.")
        return value


class RegistrationResponse(BaseModel):
    request_id: str
    received_at: datetime


class ApiKeyRequest(BaseModel):
    contact_name: str = Field(..., min_length=2, max_length=120)
    email: EmailStr
    company: str = Field(..., min_length=2, max_length=160)
    use_case: str = Field(..., min_length=10, max_length=600)
    expected_monthly_requests: str | None = Field(default=None, max_length=80)
    integration_stage: str | None = Field(default=None, max_length=80)
    timeline: str | None = Field(default=None, max_length=120)
    subscribe_updates: bool = False
    terms_accepted: bool = Field(
        ...,
        description="Explicit confirmation that the user agrees with the terms.",
    )

    @field_validator(
        "company",
        "expected_monthly_requests",
        "integration_stage",
        "timeline",
        mode="before",
    )
    @classmethod
    def _normalize_optional_api_text(cls, value: object | None) -> str | None:
        return _strip_or_none(value)

    @field_validator("use_case", mode="before")
    @classmethod
    def _normalize_use_case(cls, value: object | None) -> str:
        if value is None:
            raise ValueError("use_case is required.")
        if isinstance(value, str):
            stripped = value.strip()
            if not stripped:
                raise ValueError("use_case must not be blank.")
            return stripped
        return str(value)

    @field_validator("terms_accepted")
    @classmethod
    def _ensure_api_terms(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("terms_accepted must be true.")
        return value


class ApiKeyRequestResponse(BaseModel):
    request_id: str
    received_at: datetime


class SupportTicketAttachment(BaseModel):
    filename: str = Field(..., min_length=1, max_length=160)
    content_type: str | None = Field(default=None, max_length=120)
    content_base64: str = Field(..., min_length=4, max_length=12_000_000)

    @field_validator("filename", mode="before")
    @classmethod
    def _normalize_filename(cls, value: object | None) -> str:
        if value is None:
            raise ValueError("filename is required.")
        return str(value).strip()

    @model_validator(mode="after")
    def _validate_bytes(self) -> "SupportTicketAttachment":
        try:
            data = base64.b64decode(self.content_base64, validate=True)
        except (binascii.Error, ValueError) as exc:
            raise ValueError("Attachment content must be valid base64.") from exc
        if len(data) > SUPPORT_ATTACHMENT_MAX_BYTES:
            max_mb = round(SUPPORT_ATTACHMENT_MAX_BYTES / (1024 * 1024))
            raise ValueError(f"Attachments must be {max_mb} MB or smaller.")
        return self


class SupportTicket(BaseModel):
    subject: str = Field(..., min_length=4, max_length=160)
    description: str = Field(..., min_length=10, max_length=2000)
    contact_email: EmailStr
    contact_name: str | None = Field(default=None, max_length=120)
    attachments: list[SupportTicketAttachment] | None = None

    @field_validator("subject", "description", mode="before")
    @classmethod
    def _normalize_required_text(cls, value: object | None) -> str:
        if value is None:
            raise ValueError("This field is required.")
        if isinstance(value, str):
            stripped = value.strip()
            if not stripped:
                raise ValueError("This field must not be blank.")
            return stripped
        return str(value)

    @field_validator("contact_name", mode="before")
    @classmethod
    def _normalize_contact_name(cls, value: object | None) -> str | None:
        return _strip_or_none(value)

    @field_validator("attachments")
    @classmethod
    def _limit_attachments(cls, value: list[SupportTicketAttachment] | None) -> list[SupportTicketAttachment]:
        if not value:
            return []
        if len(value) > SUPPORT_ATTACHMENT_MAX_COUNT:
            raise ValueError(f"Up to {SUPPORT_ATTACHMENT_MAX_COUNT} attachments are allowed.")
        return value


class SupportTicketResponse(BaseModel):
    request_id: str
    received_at: datetime


class CtaEvent(BaseModel):
    cta_id: str = Field(..., min_length=2, max_length=120, pattern=r"^[A-Za-z0-9_.\-]+$")
    event_type: str | None = Field(default=None, max_length=64)
    cta_format: str | None = Field(default=None, max_length=120)
    page_path: str | None = Field(default=None, max_length=240)
    utm_source: str | None = Field(default=None, max_length=200)
    utm_medium: str | None = Field(default=None, max_length=200)
    utm_campaign: str | None = Field(default=None, max_length=200)
    utm_content: str | None = Field(default=None, max_length=200)
    utm_term: str | None = Field(default=None, max_length=200)
    actor_id: str | None = Field(default=None, max_length=160)
    account_id: str | None = Field(default=None, max_length=160)
    session_id: str | None = Field(default=None, max_length=160)
    fingerprint: str | None = Field(default=None, max_length=160)
    timestamp: datetime | None = None
    location: str | None = Field(default=None, max_length=160)
    href: str | None = Field(default=None, max_length=320)
    metadata: dict[str, Any] | None = None

    @field_validator(
        "cta_format",
        "page_path",
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_content",
        "utm_term",
        "actor_id",
        "account_id",
        "session_id",
        "fingerprint",
        "location",
        "href",
        mode="before",
    )
    @classmethod
    def _normalize_optional_text(cls, value: object | None) -> str | None:
        return _strip_or_none(value)

    @field_validator("event_type", mode="before")
    @classmethod
    def _normalize_event_type(cls, value: object | None) -> str | None:
        normalized = _strip_or_none(value)
        if normalized is None:
            return None
        lowered = normalized.lower()
        if lowered not in _CTA_EVENT_TYPES:
            raise ValueError(f"event_type must be one of: {', '.join(sorted(_CTA_EVENT_TYPES))}.")
        return lowered


class CtaEventResponse(BaseModel):
    event_id: str
    received_at: datetime


class CtaPeriodModel(BaseModel):
    start_at: datetime
    end_at: datetime
    lookback_days: int


class CtaFunnelModel(BaseModel):
    click_users: int
    signup_users: int
    confirmed_users: int
    paid_users: int
    click_to_signup: float
    click_to_confirmed: float
    signup_to_confirmed: float
    confirmed_to_paid: float
    signup_to_paid: float
    click_to_paid: float


class CtaRateModel(BaseModel):
    ctr: float
    signup_cr: float
    confirm_cr: float
    paid_cr: float


class CtaAttributionModel(BaseModel):
    model: str
    lookback_days: int
    identity_priority: list[str]


class CtaObservabilityModel(BaseModel):
    expected_slots: int
    active_slots: int
    missing_slots: int
    missing_ratio: float
    total_events: int
    invalid_events: int
    duplicate_events: int
    invalid_ratio: float
    aggregation_lag_seconds: int | None = None


class CtaLastAcceptedEventModel(BaseModel):
    event_id: str
    received_at: datetime | None = None
    cta_id: str
    location: str


class CtaLastAggregatedSlotModel(BaseModel):
    event_hour: datetime | None = None
    event_date: date | None = None


class CtaServiceStateModel(BaseModel):
    last_accepted_event: CtaLastAcceptedEventModel | None = None
    last_aggregated_slot: CtaLastAggregatedSlotModel | None = None


class AdminCtaPagination(BaseModel):
    page: int
    page_size: int
    total_items: int
    total_pages: int


class AdminCtaSummaryResponse(BaseModel):
    period: CtaPeriodModel
    total_clicks: int
    unique_clicks: int
    unique_users: int
    unique_sessions: int
    unique_anonymous: int
    conversion: CtaFunnelModel
    rates: CtaRateModel
    attribution_coverage: float
    attribution: CtaAttributionModel
    observability: CtaObservabilityModel
    service_state: CtaServiceStateModel
    generated_at: datetime


class AdminCtaTimeseriesItem(BaseModel):
    bucket: str
    total_clicks: int
    unique_clicks: int
    unique_users: int
    unique_sessions: int
    conversion: CtaFunnelModel
    rates: CtaRateModel
    attribution_coverage: float
    attribution: CtaAttributionModel


class AdminCtaTimeseriesResponse(BaseModel):
    items: list[AdminCtaTimeseriesItem]
    interval: Literal["day", "hour"]
    pagination: AdminCtaPagination
    generated_at: datetime


class AdminCtaTopItem(BaseModel):
    cta_id: str
    total_clicks: int
    unique_clicks: int
    unique_users: int
    unique_sessions: int
    conversion: CtaFunnelModel
    rates: CtaRateModel
    attribution_coverage: float
    attribution: CtaAttributionModel


class AdminCtaTopResponse(BaseModel):
    items: list[AdminCtaTopItem]
    pagination: AdminCtaPagination
    generated_at: datetime


class AdminCtaBreakdownItem(BaseModel):
    cta_id: str
    cta_format: str
    location: str
    page_path: str
    utm_source: str
    total_clicks: int
    unique_clicks: int
    unique_users: int
    unique_sessions: int
    conversion: CtaFunnelModel
    rates: CtaRateModel
    attribution_coverage: float
    attribution: CtaAttributionModel


class AdminCtaBreakdownResponse(BaseModel):
    items: list[AdminCtaBreakdownItem]
    pagination: AdminCtaPagination
    generated_at: datetime


class AdminCtaFunnelResponse(BaseModel):
    period: CtaPeriodModel
    total_clicks: int
    unique_clicks: int
    conversion: CtaFunnelModel
    rates: CtaRateModel
    attribution_coverage: float
    attribution: CtaAttributionModel
    generated_at: datetime


class CtaFormatStatusChangeModel(BaseModel):
    cta_format: str
    previous_status: Literal["active", "paused"]
    new_status: Literal["active", "paused"]
    rank: int | None = None
    ctr: float
    signup_cr: float
    total_clicks: int
    unique_clicks: int
    signup_users: int
    reason: str
    changed_at: datetime


class CtaFormatStatusModel(BaseModel):
    cta_format: str
    status: Literal["active", "paused"]
    rank: int | None = None
    ctr: float
    signup_cr: float
    total_clicks: int
    unique_clicks: int
    signup_users: int
    reason: str
    last_decision_id: int | None = None
    updated_at: datetime


class CtaFormatDecisionModel(BaseModel):
    id: int
    decided_at: datetime
    window_start_at: datetime
    window_end_at: datetime
    window_days: int
    top_n: int
    reason: str
    top_formats: list[str]
    ranking: list[dict[str, Any]] = Field(default_factory=list)
    status_changes: list[CtaFormatStatusChangeModel] = Field(default_factory=list)
    changed_formats: int


class AdminCtaFormatDecisionsResponse(BaseModel):
    period_days: int
    items: list[CtaFormatDecisionModel]
    current_statuses: list[CtaFormatStatusModel] = Field(default_factory=list)
    generated_at: datetime


AdminCtaExportDataset = Literal["summary", "timeseries", "top_cta", "breakdown", "funnel"]


class SignupRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=10, max_length=160)
    newsletter_opt_in: bool = False
    terms_version: str = Field(default="2024-01", max_length=32)
    cta_session_id: str | None = Field(default=None, max_length=120)
    source_cta_id: str | None = Field(default=None, max_length=120)
    source_page_path: str | None = Field(default=None, max_length=160)
    source_scenario: str | None = Field(default=None, max_length=120)

    @field_validator("email", mode="before")
    @classmethod
    def _normalize_email(cls, value: object | None) -> str:
        if value is None:
            raise ValueError("Email is required.")
        if isinstance(value, str):
            return value.strip().lower()
        return str(value).strip().lower()

    @field_validator("password")
    @classmethod
    def _validate_password_strength(cls, value: str) -> str:
        has_digit = any(char.isdigit() for char in value)
        has_alpha = any(char.isalpha() for char in value)
        has_special = any(not char.isalnum() for char in value)
        if not (has_digit and has_alpha and has_special):
            raise ValueError("Password must include letters, numbers, and special characters.")
        return value


class SignupResponse(BaseModel):
    account_id: str
    email: EmailStr
    status: str
    next_step: Literal["confirm_email"]
    debug_confirmation_token: str | None = None


class ConfirmEmailRequest(BaseModel):
    token: str = Field(..., min_length=16, max_length=512)


class ResendConfirmationRequest(BaseModel):
    email: EmailStr


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=8, max_length=256)


class ForgotPasswordRequest(BaseModel):
    email: EmailStr


class ResetPasswordRequest(BaseModel):
    token: str = Field(..., min_length=16, max_length=512)
    password: str = Field(..., min_length=10, max_length=256)


class OrganizationProfile(BaseModel):
    id: str | None = None
    name: str | None = None
    size_label: str | None = None
    primary_use_case: str | None = None
    country: str | None = None


class UserLimits(BaseModel):
    daily_call_limit: int | None = None
    monthly_call_limit: int | None = None
    notes: str | None = None


class SubscriptionProfile(BaseModel):
    plan_code: str
    status: str
    currency: str | None = None
    unit_amount_cents: int | None = None
    interval: str | None = None
    price_id: str | None = None
    current_period_start: datetime | None = None
    trial_ends_at: datetime | None = None
    current_period_end: datetime | None = None
    cancel_at_period_end: bool = False
    latest_invoice_id: str | None = None
    hosted_checkout_url: AnyHttpUrl | None = None


class UserProfile(BaseModel):
    id: str
    email: EmailStr
    full_name: str
    job_title: str | None = None
    status: str
    newsletter_opt_in: bool
    roles: list[str]
    use_case: str | None = None
    organization: OrganizationProfile | None = None
    email_verified_at: datetime | None = None
    last_login_at: datetime | None = None
    limits: UserLimits | None = None
    subscription: SubscriptionProfile | None = None


class ApiKeyUsageModel(BaseModel):
    unit: Literal["tokens"] = "tokens"
    daily_calls: int
    daily_quota: int | None = None
    daily_pct: float | None = None
    monthly_calls: int
    monthly_quota: int | None = None
    monthly_pct: float | None = None
    burst_per_second: int
    burst_per_minute: int
    data_latency_seconds: int


class ApiKeyModel(BaseModel):
    id: str
    label: str
    application_name: str | None = None
    tags: list[str] = Field(default_factory=list)
    role: str
    status: str
    plan_code: str
    token_preview: str
    created_at: datetime
    last_used_at: datetime | None = None
    expires_at: datetime | None = None
    revoked_at: datetime | None = None
    ip_allowlist: list[str] = Field(default_factory=list)
    label_constraints: list[str] = Field(default_factory=list)
    usage: ApiKeyUsageModel


class ApiKeyPlanLimits(BaseModel):
    daily_quota: int | None = None
    monthly_quota: int | None = None
    burst_per_second: int
    burst_per_minute: int
    data_latency_seconds: int


class ApiKeyListResponse(BaseModel):
    keys: list[ApiKeyModel]
    plan_code: str
    max_keys: int
    allowed_roles: list[str]
    plan_limits: ApiKeyPlanLimits
    monthly_usage_total: int = 0


def _coerce_string_sequence(value: object | None) -> list[str] | None:
    if value is None:
        return None
    if isinstance(value, str):
        raw_values = value.split(",")
    elif isinstance(value, (list, tuple, set)):
        raw_values = value
    else:
        return None
    cleaned: list[str] = []
    for item in raw_values:
        candidate = str(item).strip()
        if not candidate:
            continue
        cleaned.append(candidate)
        if len(cleaned) >= 32:
            break
    return cleaned or None


class ApiKeyCreateRequest(BaseModel):
    label: str = Field(..., min_length=3, max_length=160)
    application_name: str | None = Field(default=None, max_length=160)
    tags: list[str] | None = Field(default=None)
    role: str | None = Field(default=None, max_length=40)
    ip_allowlist: list[str] | None = Field(default=None)
    label_constraints: list[str] | None = Field(default=None)

    @field_validator("tags", mode="before")
    @classmethod
    def _normalize_tags(cls, value: object | None) -> list[str] | None:
        if value is None:
            return None
        values: list[str]
        if isinstance(value, str):
            values = [value]
        elif isinstance(value, (list, tuple, set)):
            values = [str(item) for item in value]
        else:
            return None
        cleaned: list[str] = []
        for item in values:
            trimmed = item.strip()
            if not trimmed:
                continue
            cleaned.append(trimmed[:40])
            if len(cleaned) >= 8:
                break
        return cleaned or None

    @field_validator("ip_allowlist", mode="before")
    @classmethod
    def _normalize_ip_allowlist(cls, value: object | None) -> list[str] | None:
        values = _coerce_string_sequence(value)
        if not values:
            return None
        cleaned: list[str] = []
        for item in values:
            cleaned.append(item[:96])
            if len(cleaned) >= 16:
                break
        return cleaned or None

    @field_validator("label_constraints", mode="before")
    @classmethod
    def _normalize_label_constraints(cls, value: object | None) -> list[str] | None:
        values = _coerce_string_sequence(value)
        if not values:
            return None
        cleaned: list[str] = []
        for item in values:
            normalized = item.lower()
            cleaned.append(normalized[:40])
            if len(cleaned) >= 8:
                break
        return cleaned or None


class ApiKeyRevokeRequest(BaseModel):
    reason: str | None = Field(default=None, max_length=400)


class ApiKeyUpdateRequest(BaseModel):
    label: str | None = Field(default=None, min_length=3, max_length=160)
    application_name: str | None = Field(default=None, max_length=160)
    tags: list[str] | None = Field(default=None)
    role: str | None = Field(default=None, max_length=40)
    ip_allowlist: list[str] | None = Field(default=None)
    label_constraints: list[str] | None = Field(default=None)

    @field_validator("tags", mode="before")
    @classmethod
    def _normalize_tags(cls, value: object | None) -> list[str] | None:
        return ApiKeyCreateRequest._normalize_tags(value)

    @field_validator("ip_allowlist", mode="before")
    @classmethod
    def _normalize_ip_allowlist(cls, value: object | None) -> list[str] | None:
        return ApiKeyCreateRequest._normalize_ip_allowlist(value)

    @field_validator("label_constraints", mode="before")
    @classmethod
    def _normalize_label_constraints(cls, value: object | None) -> list[str] | None:
        return ApiKeyCreateRequest._normalize_label_constraints(value)


class ApiKeyStatusUpdateRequest(BaseModel):
    status: Literal["active", "disabled", "revoked"]
    reason: str | None = Field(default=None, max_length=400)


class ApiKeyMaterializedResponse(BaseModel):
    key: ApiKeyModel
    secret: str


class ApiKeyActivityModel(BaseModel):
    id: str
    event_type: str
    actor: str | None = None
    actor_ip: str | None = None
    description: str
    created_at: datetime
    metadata: dict[str, object] | None = None


class ApiKeyActivityListResponse(BaseModel):
    events: list[ApiKeyActivityModel]


class AdminApiKeyModel(ApiKeyModel):
    account_id: str
    account_email: EmailStr
    account_status: str


class AdminApiKeyListResponse(BaseModel):
    keys: list[AdminApiKeyModel]


class BillingCheckoutRequest(BaseModel):
    plan_code: Literal["free", "pro", "ultra", "enterprise"] = "pro"


class BillingCheckoutResponse(BaseModel):
    checkout_url: AnyHttpUrl
    session_id: str


class BillingCryptoCheckoutResponse(BaseModel):
    hosted_url: AnyHttpUrl
    invoice_id: str


class BillingPortalResponse(BaseModel):
    portal_url: AnyHttpUrl


class BillingCancelRequest(BaseModel):
    plan_code: str | None = None
    resume: bool = False


class BillingCancelResponse(BaseModel):
    subscription: SubscriptionProfile | None = None
    expired_invoice_ids: list[str] = Field(default_factory=list)


class BillingStatusResponse(BaseModel):
    subscription: SubscriptionProfile | None = None
    account_status: str | None = None
    email_verified: bool = False


class UsageSeriesPoint(BaseModel):
    date: date
    call_count: int
    error_count: int


class UsageTotals(BaseModel):
    unit: Literal["tokens"] = "tokens"
    total_calls: int
    average_per_day: float
    max_calls: int
    total_errors: int
    monthly_usage: int
    monthly_quota: int | None = None
    plan_code: str


class UsageSummaryResponse(BaseModel):
    window_days: int
    points: list[UsageSeriesPoint]
    totals: UsageTotals


class UsageErrorEntry(BaseModel):
    route_path: str
    route_name: str | None = None
    status_code: int
    error_code: str | None = None
    occurrences: int
    last_seen: datetime


class UsageErrorsResponse(BaseModel):
    window_days: int
    errors: list[UsageErrorEntry]


class UsageAlertChannel(BaseModel):
    id: str
    channel_type: Literal["email", "slack"]
    destination: str
    label: str | None = None
    threshold_percent: int
    enabled: bool
    last_triggered_at: datetime | None = None


class UsageAlertConfig(BaseModel):
    channel_type: Literal["email", "slack"]
    destination: str
    label: str | None = None
    threshold_percent: int = Field(80, ge=10, le=1000)
    enabled: bool = True

    @model_validator(mode="after")
    def _validate_destination(self) -> UsageAlertConfig:
        normalized = (self.destination or "").strip()
        if self.channel_type == "email":
            _EMAIL_VALIDATOR.validate_python(normalized)
        else:
            _URL_VALIDATOR.validate_python(normalized)
        self.destination = normalized
        return self


class UsageAlertListResponse(BaseModel):
    alerts: list[UsageAlertChannel]


class UsageAlertUpdateRequest(BaseModel):
    alerts: list[UsageAlertConfig]


class BillingEnterpriseInvoiceRequest(BaseModel):
    amount_cents: int = Field(..., ge=1000, le=5_000_000)
    memo: str = Field(..., min_length=4, max_length=200)
    due_in_days: int | None = Field(default=None, ge=1, le=90)


class BillingEnterpriseInvoiceResponse(BaseModel):
    invoice_id: str
    hosted_invoice_url: AnyHttpUrl | None = None
    due_date: datetime | None = None


class BillingEnterpriseExtendRequest(BaseModel):
    additional_days: int = Field(..., ge=1, le=365)
    note: str | None = Field(default=None, max_length=300)


class AuthSessionResponse(BaseModel):
    access_token: str
    token_type: Literal["bearer"] = "bearer"
    expires_in: int
    profile: UserProfile
    debug_refresh_token: str | None = None


class SimpleMessageResponse(BaseModel):
    message: str


class PasswordResetRequestResponse(SimpleMessageResponse):
    debug_reset_token: str | None = None


class AdminUpdateStatusRequest(BaseModel):
    status: Literal["pending_activation", "active", "locked", "invited"]


class AdminUpdateLimitsRequest(BaseModel):
    daily_call_limit: int | None = Field(default=None, ge=0)
    monthly_call_limit: int | None = Field(default=None, ge=0)
    notes: str | None = Field(default=None, max_length=400)


class AdminUpdatePlanRequest(BaseModel):
    plan_code: str = Field(..., min_length=2, max_length=64)
    status: Literal[
        "trialing",
        "active",
        "past_due",
        "canceled",
        "incomplete",
        "incomplete_expired",
        "unpaid",
    ] = "active"
    current_period_end: datetime | None = None

    @field_validator("plan_code", mode="before")
    @classmethod
    def _normalize_plan_code(cls, value: object | None) -> str:
        if value is None:
            raise ValueError("plan_code is required.")
        return str(value).strip().lower()


class AdminUpdateRolesRequest(BaseModel):
    roles: list[str] = Field(default_factory=list)

    @field_validator("roles", mode="before")
    @classmethod
    def _normalize_roles(cls, value: object | None) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            candidate = value.strip().lower()
            return [candidate] if candidate else []
        roles: list[str] = []
        for role in value or []:
            candidate = str(role or "").strip().lower()
            if candidate:
                roles.append(candidate)
        return roles


class AdminPerformanceConfigRequest(BaseModel):
    enabled: bool | None = None
    next_run_date: date | None = None

    @field_validator("enabled", mode="before")
    @classmethod
    def _normalize_enabled(cls, value: object | None) -> bool | None:
        if value is None or isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().lower()
            if lowered in _BOOLEAN_TRUTHY:
                return True
            if lowered in _BOOLEAN_FALSY:
                return False
        raise ValueError("enabled must be true/false when provided.")

    @field_validator("next_run_date", mode="before")
    @classmethod
    def _normalize_next_run_date(cls, value: object | None) -> date | None:
        if value is None:
            return None
        if isinstance(value, str) and not value.strip():
            return None
        return value


class PerformanceAutoConfigModel(BaseModel):
    enabled: bool
    next_run_date: date | None = None
    last_run_at: datetime | None = None
    last_run_status: str | None = None
    last_error: str | None = None
    last_summary: dict[str, object] | None = None


class PerformanceRunState(BaseModel):
    state: Literal["idle", "running", "error"] = "idle"
    reason: str | None = None
    started_at: datetime | None = None
    last_run_at: datetime | None = None
    last_status: str | None = None
    last_error: str | None = None
    is_running: bool = False


class AdminPerformanceStatus(BaseModel):
    config: PerformanceAutoConfigModel
    snapshots: list[dict[str, object]]
    benchmarks: list[dict[str, object]]
    runtime: PerformanceRunState
    report: dict[str, object] | None = None


class AdminIndexAutoStatus(BaseModel):
    config: PerformanceAutoConfigModel
    runtime: PerformanceRunState
    last_run_id: str | None = None
    last_summary: dict[str, object] | None = None
    strategy_runs: list[dict[str, object]] = Field(default_factory=list)


class ProfileUpdateRequest(BaseModel):
    email: EmailStr | None = None
    full_name: str | None = Field(default=None, min_length=2, max_length=160)
    job_title: str | None = Field(default=None, max_length=120)
    organization_name: str | None = Field(default=None, max_length=160)
    organization_size: str | None = Field(default=None, max_length=60)
    use_case: str | None = Field(default=None, max_length=400)
    no_company: bool = False

    @field_validator("email", mode="before")
    @classmethod
    def _normalize_profile_email(cls, value: object | None) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            normalized = value.strip().lower()
            return normalized or None
        return str(value).strip().lower()

    @field_validator("full_name", "job_title", "organization_name", "organization_size", "use_case", mode="before")
    @classmethod
    def _normalize_profile_text(cls, value: object | None) -> str | None:
        return _strip_or_none(value)

