-- Step 5: weekly CTA format optimization decisions and status tracking.
-- Target DB: PostgreSQL (aici_auth, auth-db service).

CREATE TABLE IF NOT EXISTS cta_format_optimization_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decided_at TEXT NOT NULL,
    window_start_at TEXT NOT NULL,
    window_end_at TEXT NOT NULL,
    window_days INTEGER NOT NULL,
    top_n INTEGER NOT NULL,
    reason TEXT NOT NULL,
    ranking_json JSONB NOT NULL,
    top_formats_json JSONB NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cta_format_optimization_runs_decided_at
    ON cta_format_optimization_runs(decided_at DESC);

CREATE TABLE IF NOT EXISTS cta_format_status_current (
    cta_format TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    rank INTEGER,
    ctr DOUBLE PRECISION NOT NULL DEFAULT 0,
    signup_cr DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    unique_clicks INTEGER NOT NULL DEFAULT 0,
    signup_users INTEGER NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    last_decision_id BIGINT,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cta_format_status_current_status
    ON cta_format_status_current(status);

CREATE TABLE IF NOT EXISTS cta_format_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id BIGINT NOT NULL,
    cta_format TEXT NOT NULL,
    previous_status TEXT,
    new_status TEXT NOT NULL,
    rank INTEGER,
    ctr DOUBLE PRECISION NOT NULL DEFAULT 0,
    signup_cr DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    unique_clicks INTEGER NOT NULL DEFAULT 0,
    signup_users INTEGER NOT NULL DEFAULT 0,
    change_reason TEXT NOT NULL,
    changed_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cta_format_status_log_decision_id
    ON cta_format_status_log(decision_id);

CREATE INDEX IF NOT EXISTS ix_cta_format_status_log_changed_at
    ON cta_format_status_log(changed_at DESC);
