-- Step 5: CTA analytics persistent storage and aggregation layer.
-- Target DB: PostgreSQL (aici_auth, auth-db service).

CREATE TABLE IF NOT EXISTS cta_events_fact (
    event_id TEXT PRIMARY KEY,
    received_at TEXT NOT NULL,
    event_date TEXT NOT NULL,
    event_hour TEXT NOT NULL,
    cta_id TEXT NOT NULL,
    location TEXT NOT NULL,
    location_norm TEXT NOT NULL,
    page_path TEXT,
    section TEXT,
    href TEXT,
    referer TEXT,
    user_agent TEXT,
    device_type TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_content TEXT,
    utm_term TEXT,
    unique_actor_id TEXT NOT NULL,
    metadata_json TEXT NOT NULL,
    dedup_signature TEXT,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cta_events_fact_received_at
    ON cta_events_fact(received_at);
CREATE INDEX IF NOT EXISTS ix_cta_events_fact_event_date_cta_id
    ON cta_events_fact(event_date, cta_id);
CREATE INDEX IF NOT EXISTS ix_cta_events_fact_event_hour_cta_id
    ON cta_events_fact(event_hour, cta_id);
CREATE INDEX IF NOT EXISTS ix_cta_events_fact_cta_received_at
    ON cta_events_fact(cta_id, received_at);
CREATE INDEX IF NOT EXISTS ix_cta_events_fact_actor_received_at
    ON cta_events_fact(unique_actor_id, received_at);

CREATE TABLE IF NOT EXISTS cta_metrics_hourly (
    event_hour TEXT NOT NULL,
    event_date TEXT NOT NULL,
    cta_id TEXT NOT NULL,
    location_norm TEXT NOT NULL,
    device_type TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    unique_clicks INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (event_hour, cta_id, location_norm, device_type, auth_state)
);

CREATE INDEX IF NOT EXISTS ix_cta_metrics_hourly_cta_hour
    ON cta_metrics_hourly(cta_id, event_hour);
CREATE INDEX IF NOT EXISTS ix_cta_metrics_hourly_date
    ON cta_metrics_hourly(event_date);

CREATE TABLE IF NOT EXISTS cta_metrics_daily (
    event_date TEXT NOT NULL,
    cta_id TEXT NOT NULL,
    location_norm TEXT NOT NULL,
    device_type TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    unique_clicks INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (event_date, cta_id, location_norm, device_type, auth_state)
);

CREATE INDEX IF NOT EXISTS ix_cta_metrics_daily_cta_date
    ON cta_metrics_daily(cta_id, event_date);

CREATE TABLE IF NOT EXISTS cta_metrics_hourly_actor_unique (
    event_hour TEXT NOT NULL,
    cta_id TEXT NOT NULL,
    location_norm TEXT NOT NULL,
    device_type TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    unique_actor_id TEXT NOT NULL,
    first_seen_at TEXT NOT NULL,
    PRIMARY KEY (event_hour, cta_id, location_norm, device_type, auth_state, unique_actor_id)
);

CREATE TABLE IF NOT EXISTS cta_metrics_daily_actor_unique (
    event_date TEXT NOT NULL,
    cta_id TEXT NOT NULL,
    location_norm TEXT NOT NULL,
    device_type TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    unique_actor_id TEXT NOT NULL,
    first_seen_at TEXT NOT NULL,
    PRIMARY KEY (event_date, cta_id, location_norm, device_type, auth_state, unique_actor_id)
);

CREATE TABLE IF NOT EXISTS cta_fact_retention_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT NOT NULL,
    cutoff_at TEXT NOT NULL,
    archived_rows INTEGER NOT NULL,
    deleted_rows INTEGER NOT NULL,
    archive_path TEXT,
    status TEXT NOT NULL,
    error_message TEXT
);

-- Step 10: CTA observability and data-quality diagnostics.
-- Target DB: PostgreSQL (aici_auth, auth-db service).

CREATE TABLE IF NOT EXISTS cta_ingestion_quality_hourly (
    event_hour TEXT PRIMARY KEY,
    total_events INTEGER NOT NULL DEFAULT 0,
    accepted_events INTEGER NOT NULL DEFAULT 0,
    duplicate_events INTEGER NOT NULL DEFAULT 0,
    invalid_events INTEGER NOT NULL DEFAULT 0,
    last_event_id TEXT,
    last_received_at TEXT,
    last_error_reason TEXT,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cta_ingestion_quality_hourly_updated_at
    ON cta_ingestion_quality_hourly(updated_at);
